# FastAPI Service for Network Access
# This file creates a Kubernetes service that provides stable network access
# to your FastAPI pods, enabling load balancing and service discovery

apiVersion: v1
kind: Service
metadata:
  name: fastapi-service-dev-chris
  namespace: dev-chris
  labels:
    app: fastapi-dev-chris
    branch: dev-chris
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: fastapi-dev-chris
