# Grafana Service for Monitoring Access
# This file creates a Kubernetes service that provides network access
# to your Grafana instance for dashboard visualization

apiVersion: v1
kind: Service
metadata:
  name: grafana-service-dev-chris
  namespace: dev-chris
  labels:
    app: grafana-dev-chris
    branch: dev-chris
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: grafana-dev-chris
