# Prometheus Service for Monitoring Access
# This file creates a Kubernetes service that provides network access
# to your Prometheus instance for metrics collection and web interface

apiVersion: v1
kind: Service
metadata:
  name: prometheus-service-dev-chris
  namespace: dev-chris
  labels:
    app: prometheus-dev-chris
    branch: dev-chris
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: prometheus-dev-chris
