version: '3.8'

services:

  preprocessing:
    build:
      context: .
      dockerfile: docker/Dockerfile.preprocessing
    volumes:
      - ./data:/app/data
    command: ["python", "src/data/make_dataset.py"]

  train:
    build:
      context: .
      dockerfile: docker/Dockerfile.train
    depends_on:
      - preprocessing
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    command: ["python", "src/models/train_model_text_mlflow.py"]

  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    command: ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5000"]

volumes:
  data:
  models:
  mlruns:
