version: '3.8'

services:

  preprocessing:
    build:
      context: .
      dockerfile: docker/Dockerfile.preprocessing
    volumes:
      - ./data:/app/data
    command: ["python", "-m", "src.data.make_dataset"]

  train:
    build:
      context: .
      dockerfile: docker/Dockerfile.train
    depends_on:
      - preprocessing
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    command: ["python", "-m", "src.models.train_model_mlflow"]

  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    command: ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5000"]

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    depends_on:
      - train
    volumes:
      - ./src:/app/src
      - ./data/processed:/app/data/processed
      - ./models:/app/models
    ports:
      - "8000:8000"
    command: ["uvicorn", "src.api.service:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  data:
  models:
  mlruns:
