# Ratio of data to be used for training and testing (in order to avoid long model training on AWS GPU)
data_ratio : 0.1

# Definition of the data split parameters
data_split : 
  validation_size : 0.15
  test_size : 0.15
  random_state : 42
  shuffle : true


