apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-models
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/dransi/MAI25_CMLOps_Rakuten/models"
    type: Directory