apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeName: pv-data