apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-models
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-path
  volumeName: pv-models