apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-dev-chris
  namespace: dev-chris
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/ubuntu/mai25_CMLops/MAI25_CMLOps_Rakuten_dev_chris/data
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc-dev-chris
  namespace: dev-chris
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage 