FROM apache/airflow:2.9.1

# Become root to install packages and create folders
USER root

# Install your packages
RUN apt-get update && \
    apt-get install -y curl unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create folders and set permissions
RUN mkdir -p /opt/airflow/dags /opt/airflow/logs && \
    chown -R airflow: /opt/airflow/dags /opt/airflow/logs

# Switch back to airflow user
USER airflow
