FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY .env /app/.env
#COPY src/ app/src/
COPY params.yaml /app/params.yaml
COPY src/data/make_dataset.py /app/src/data/make_dataset.py
COPY src/tools/tools.py /app/src/tools/tools.py

CMD ["python", "-m", "src.data.make_dataset"]
