FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install transformers tensorflow

COPY . .

CMD ["python -m", "src.models.train_model_text_mlflow"]
