FROM python:3.12-slim

WORKDIR /app

COPY docker/requirements.evidently.txt .
RUN pip install --no-cache-dir -r requirements.evidently.txt

COPY src/ /app/src/
COPY params.yaml .
COPY setup.py .
COPY .env /app/.env