apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "${BASE_DIR}/data"
    type: Directory