apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-models
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "${BASE_DIR}/models"
    type: Directory