# Prometheus Configuration for MLOps Monitoring
# This ConfigMap contains the Prometheus configuration file
# It defines what targets to monitor and how often to collect metrics

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-dev-chris
  namespace: dev-chris
  labels:
    app: prometheus-dev-chris
    branch: dev-chris
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'fastapi-dev-chris'
        static_configs:
          - targets: ['fastapi-service-dev-chris:8000']
        metrics_path: /metrics
        scrape_interval: 5s
      
      - job_name: 'prometheus-dev-chris'
        static_configs:
          - targets: ['localhost:9090']
